<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Programa</name>
   <tag></tag>
   <elementGuidId>f63ed0f8-dc3f-4e21-9efb-96a7db090612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='125:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>125:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>137:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Programa de interés</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOCTORADO EN CIENCIAS DE LA DIRECCIÓNESP EN GEREN. DE LA SEGURIDAD Y SALUD EN EL TRABAJO-PROG.EN CONV DE EXTEN.TITULO OTORGA POR U CESESPECIALIZACION EN AUDITORIA EN SALUD-PROG. EN CONV DE EXTENSIÓN. TITULO OTORGADO POR LA U.CESESPECIALIZACIÓN EN GERENCIA DE EMPRESASESPECIALIZACIÓN EN GERENCIA DE MERCADEOESPECIALIZACIÓN EN GERENCIA DE NEGOCIOS INTERNACIONALESESPECIALIZACIÓN EN GERENCIA DE PROYECTOS DE CONSTRUCCIÓN E INFRAESTRUCTURAESPECIALIZACIÓN EN GERENCIA DE PROYECTOS DE SERVICIOS CON TICESPECIALIZACIÓN EN GERENCIA EN GESTIÓN HUMANA Y DESARROLLO ORGANIZACIONALESPECIALIZACIÓN EN GERENCIA INTEGRAL DE SERVICIOS DE SALUDESPECIALIZACIÓN EN GERENCIA INTEGRAL DE SERVICIOS DE SALUD -  MODALIDAD VIRTUALMAESTRÍA EN ADMINISTRACIÓN – MBA EXECUTIVEMAESTRÍA EN ADMINISTRACIÓN - MBA FULL TIMEMAESTRÍA EN ADMINISTRACIÓN - MBA PART TIMEMAESTRÍA EN ADMINISTRACIÓN EN SALUDMAESTRIA EN DIRECCIÓNMAESTRÍA EN EMPRENDIMIENTO E INNOVACIÓNMAESTRÍA EN MARKETING</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;125:0&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='125:0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CmpFormulario']/form/div[2]/div/div[3]/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil del programa'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoría de inscripción'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
